
/* Automatically generated struct definitions for the Data API.
 * Do not edit manually, changes will be overwritten.           */

#define RNA_RUNTIME

#include <float.h>
#include <stdio.h>
#include <limits.h>
#include <string.h>

#include <stddef.h>

#include "MEM_guardedalloc.h"

#include "DNA_ID.h"
#include "DNA_scene_types.h"
#include "BLI_blenlib.h"

#include "BLI_utildefines.h"

#include "BKE_context.h"
#include "BKE_library.h"
#include "BKE_main.h"
#include "BKE_report.h"
#include "RNA_define.h"
#include "RNA_types.h"
#include "rna_internal.h"

#include "rna_prototypes_gen.h"

#include "rna_cachefile.c"

#pragma GCC diagnostic ignored "-Wunused-parameter"

/* Autogenerated Functions */


extern CollectionPropertyRNA rna_ID_rna_properties;
extern PointerPropertyRNA rna_ID_rna_type;
extern StringPropertyRNA rna_ID_name;
extern StringPropertyRNA rna_ID_name_full;
extern BoolPropertyRNA rna_ID_is_evaluated;
extern PointerPropertyRNA rna_ID_original;
extern IntPropertyRNA rna_ID_users;
extern BoolPropertyRNA rna_ID_use_fake_user;
extern BoolPropertyRNA rna_ID_tag;
extern BoolPropertyRNA rna_ID_is_library_indirect;
extern PointerPropertyRNA rna_ID_library;
extern PointerPropertyRNA rna_ID_override_static;
extern PointerPropertyRNA rna_ID_preview;

StringPropertyRNA rna_CacheFile_filepath;
BoolPropertyRNA rna_CacheFile_is_sequence;
BoolPropertyRNA rna_CacheFile_override_frame;
FloatPropertyRNA rna_CacheFile_frame;
FloatPropertyRNA rna_CacheFile_frame_offset;
EnumPropertyRNA rna_CacheFile_forward_axis;
EnumPropertyRNA rna_CacheFile_up_axis;
FloatPropertyRNA rna_CacheFile_scale;
CollectionPropertyRNA rna_CacheFile_object_paths;
PointerPropertyRNA rna_CacheFile_animation_data;

extern FunctionRNA rna_ID_copy_func;
extern PointerPropertyRNA rna_ID_copy_id;

extern FunctionRNA rna_ID_override_create_func;
extern PointerPropertyRNA rna_ID_override_create_id;

extern FunctionRNA rna_ID_user_clear_func;
extern FunctionRNA rna_ID_user_remap_func;
extern PointerPropertyRNA rna_ID_user_remap_new_id;

extern FunctionRNA rna_ID_make_local_func;
extern BoolPropertyRNA rna_ID_make_local_clear_proxy;
extern PointerPropertyRNA rna_ID_make_local_id;

extern FunctionRNA rna_ID_user_of_id_func;
extern PointerPropertyRNA rna_ID_user_of_id_id;
extern IntPropertyRNA rna_ID_user_of_id_count;

extern FunctionRNA rna_ID_animation_data_create_func;
extern PointerPropertyRNA rna_ID_animation_data_create_anim_data;

extern FunctionRNA rna_ID_animation_data_clear_func;
extern FunctionRNA rna_ID_update_tag_func;
extern EnumPropertyRNA rna_ID_update_tag_refresh;



CollectionPropertyRNA rna_AlembicObjectPaths_rna_properties;
PointerPropertyRNA rna_AlembicObjectPaths_rna_type;


CollectionPropertyRNA rna_AlembicObjectPath_rna_properties;
PointerPropertyRNA rna_AlembicObjectPath_rna_type;
StringPropertyRNA rna_AlembicObjectPath_path;

void CacheFile_filepath_get(PointerRNA *ptr, char *value)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    BLI_strncpy(value, data->filepath, 1024);
}

int CacheFile_filepath_length(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return strlen(data->filepath);
}

void CacheFile_filepath_set(PointerRNA *ptr, const char *value)
{
    rna_CacheFile_filename_set(ptr, value);
}

bool CacheFile_is_sequence_get(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return (bool)(data->is_sequence);
}

void CacheFile_is_sequence_set(PointerRNA *ptr, bool value)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    data->is_sequence = value;
}

bool CacheFile_override_frame_get(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return (bool)(data->override_frame);
}

void CacheFile_override_frame_set(PointerRNA *ptr, bool value)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    data->override_frame = value;
}

float CacheFile_frame_get(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return (float)(data->frame);
}

void CacheFile_frame_set(PointerRNA *ptr, float value)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    data->frame = CLAMPIS(value, -1048574.0f, 1048574.0f);
}

float CacheFile_frame_offset_get(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return (float)(data->frame_offset);
}

void CacheFile_frame_offset_set(PointerRNA *ptr, float value)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    data->frame_offset = CLAMPIS(value, -1048574.0f, 1048574.0f);
}

int CacheFile_forward_axis_get(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return (int)(data->forward_axis);
}

void CacheFile_forward_axis_set(PointerRNA *ptr, int value)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    data->forward_axis = value;
}

int CacheFile_up_axis_get(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return (int)(data->up_axis);
}

void CacheFile_up_axis_set(PointerRNA *ptr, int value)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    data->up_axis = value;
}

float CacheFile_scale_get(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return (float)(data->scale);
}

void CacheFile_scale_set(PointerRNA *ptr, float value)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    data->scale = CLAMPIS(value, 0.0001000000f, 1000.0f);
}

static PointerRNA CacheFile_object_paths_get(CollectionPropertyIterator *iter)
{
    return rna_pointer_inherit_refine(&iter->parent, &RNA_AlembicObjectPath, rna_iterator_listbase_get(iter));
}

void CacheFile_object_paths_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

    memset(iter, 0, sizeof(*iter));
    iter->parent = *ptr;
    iter->prop = (PropertyRNA *)&rna_CacheFile_object_paths;

    rna_CacheFile_object_paths_begin(iter, ptr);

    if (iter->valid)
        iter->ptr = CacheFile_object_paths_get(iter);
}

void CacheFile_object_paths_next(CollectionPropertyIterator *iter)
{
    rna_iterator_listbase_next(iter);

    if (iter->valid)
        iter->ptr = CacheFile_object_paths_get(iter);
}

void CacheFile_object_paths_end(CollectionPropertyIterator *iter)
{
    rna_iterator_listbase_end(iter);
}

int CacheFile_object_paths_lookup_int(PointerRNA *ptr, int index, PointerRNA *r_ptr)
{
    int found = 0;
    CollectionPropertyIterator iter;

    CacheFile_object_paths_begin(&iter, ptr);

    if (iter.valid) {
        ListBaseIterator *internal = &iter.internal.listbase;
        if (internal->skip) {
            while (index-- > 0 && iter.valid) {
                rna_iterator_listbase_next(&iter);
            }
            found = (index == -1 && iter.valid);
        }
        else {
            while (index-- > 0 && internal->link)
                internal->link = internal->link->next;
            found = (index == -1 && internal->link);
        }
        if (found) *r_ptr = CacheFile_object_paths_get(&iter);
    }

    CacheFile_object_paths_end(&iter);

    return found;
}

int CacheFile_object_paths_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
    extern int AlembicObjectPath_path_length(PointerRNA *);
    extern void AlembicObjectPath_path_get(PointerRNA *, char *);

    bool found = false;
    CollectionPropertyIterator iter;
    char namebuf[1024];
    char *name;

    CacheFile_object_paths_begin(&iter, ptr);

    while (iter.valid) {
        if (iter.ptr.data) {
            int namelen = AlembicObjectPath_path_length(&iter.ptr);
            if (namelen < 1024) {
                AlembicObjectPath_path_get(&iter.ptr, namebuf);
                if (strcmp(namebuf, key) == 0) {
                    found = true;
                    *r_ptr = iter.ptr;
                    break;
                }
            }
            else {
                name = MEM_mallocN(namelen+1, "name string");
                AlembicObjectPath_path_get(&iter.ptr, name);
                if (strcmp(name, key) == 0) {
                    MEM_freeN(name);

                    found = true;
                    *r_ptr = iter.ptr;
                    break;
                }
                else {
                    MEM_freeN(name);
                }
            }
        }
        CacheFile_object_paths_next(&iter);
    }
    CacheFile_object_paths_end(&iter);

    return found;
}

PointerRNA CacheFile_animation_data_get(PointerRNA *ptr)
{
    CacheFile *data = (CacheFile *)(ptr->data);
    return rna_pointer_inherit_refine(ptr, &RNA_AnimData, data->adt);
}

static PointerRNA AlembicObjectPaths_rna_properties_get(CollectionPropertyIterator *iter)
{
    return rna_builtin_properties_get(iter);
}

void AlembicObjectPaths_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

    memset(iter, 0, sizeof(*iter));
    iter->parent = *ptr;
    iter->prop = (PropertyRNA *)&rna_AlembicObjectPaths_rna_properties;

    rna_builtin_properties_begin(iter, ptr);

    if (iter->valid)
        iter->ptr = AlembicObjectPaths_rna_properties_get(iter);
}

void AlembicObjectPaths_rna_properties_next(CollectionPropertyIterator *iter)
{
    rna_builtin_properties_next(iter);

    if (iter->valid)
        iter->ptr = AlembicObjectPaths_rna_properties_get(iter);
}

void AlembicObjectPaths_rna_properties_end(CollectionPropertyIterator *iter)
{
    rna_iterator_listbase_end(iter);
}

int AlembicObjectPaths_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
    return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA AlembicObjectPaths_rna_type_get(PointerRNA *ptr)
{
    return rna_builtin_type_get(ptr);
}

static PointerRNA AlembicObjectPath_rna_properties_get(CollectionPropertyIterator *iter)
{
    return rna_builtin_properties_get(iter);
}

void AlembicObjectPath_rna_properties_begin(CollectionPropertyIterator *iter, PointerRNA *ptr)
{

    memset(iter, 0, sizeof(*iter));
    iter->parent = *ptr;
    iter->prop = (PropertyRNA *)&rna_AlembicObjectPath_rna_properties;

    rna_builtin_properties_begin(iter, ptr);

    if (iter->valid)
        iter->ptr = AlembicObjectPath_rna_properties_get(iter);
}

void AlembicObjectPath_rna_properties_next(CollectionPropertyIterator *iter)
{
    rna_builtin_properties_next(iter);

    if (iter->valid)
        iter->ptr = AlembicObjectPath_rna_properties_get(iter);
}

void AlembicObjectPath_rna_properties_end(CollectionPropertyIterator *iter)
{
    rna_iterator_listbase_end(iter);
}

int AlembicObjectPath_rna_properties_lookup_string(PointerRNA *ptr, const char *key, PointerRNA *r_ptr)
{
    return rna_builtin_properties_lookup_string(ptr, key, r_ptr);
}

PointerRNA AlembicObjectPath_rna_type_get(PointerRNA *ptr)
{
    return rna_builtin_type_get(ptr);
}

void AlembicObjectPath_path_get(PointerRNA *ptr, char *value)
{
    AlembicObjectPath *data = (AlembicObjectPath *)(ptr->data);
    BLI_strncpy_utf8(value, data->path, 4096);
}

int AlembicObjectPath_path_length(PointerRNA *ptr)
{
    AlembicObjectPath *data = (AlembicObjectPath *)(ptr->data);
    return strlen(data->path);
}

void AlembicObjectPath_path_set(PointerRNA *ptr, const char *value)
{
    AlembicObjectPath *data = (AlembicObjectPath *)(ptr->data);
    BLI_strncpy_utf8(data->path, value, 4096);
}




/* CacheFile */
StringPropertyRNA rna_CacheFile_filepath = {
	{(PropertyRNA *)&rna_CacheFile_is_sequence, NULL,
	-1, "filepath", 262145, 0, 0, 0, 0, "File Path",
	"Path to external displacements file",
	0, "*",
	PROP_STRING, PROP_FILEPATH | PROP_UNIT_NONE, NULL, 0, {1024, 0, 0}, 0,
	rna_CacheFile_update_handle, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, NULL},
	CacheFile_filepath_get, CacheFile_filepath_length, CacheFile_filepath_set, NULL, NULL, NULL, 1024, ""
};

BoolPropertyRNA rna_CacheFile_is_sequence = {
	{(PropertyRNA *)&rna_CacheFile_override_frame, (PropertyRNA *)&rna_CacheFile_filepath,
	-1, "is_sequence", 3, 0, 0, 4, 0, "Sequence",
	"Whether the cache is separated in a series of files",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_CacheFile_update, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	offsetof(CacheFile, is_sequence), 2, NULL},
	CacheFile_is_sequence_get, CacheFile_is_sequence_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

BoolPropertyRNA rna_CacheFile_override_frame = {
	{(PropertyRNA *)&rna_CacheFile_frame, (PropertyRNA *)&rna_CacheFile_is_sequence,
	-1, "override_frame", 3, 0, 0, 4, 0, "Override Frame",
	"Whether to use a custom frame for looking up data in the cache file, instead of using the current scene frame",
	0, "*",
	PROP_BOOLEAN, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_CacheFile_update, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	offsetof(CacheFile, override_frame), 2, NULL},
	CacheFile_override_frame_get, CacheFile_override_frame_set, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL
};

FloatPropertyRNA rna_CacheFile_frame = {
	{(PropertyRNA *)&rna_CacheFile_frame_offset, (PropertyRNA *)&rna_CacheFile_override_frame,
	-1, "frame", 3, 0, 0, 4, 0, "Frame",
	"The time to use for looking up the data in the cache file, or to determine which file to use in a file sequence",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_CacheFile_update, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	offsetof(CacheFile, frame), 5, NULL},
	CacheFile_frame_get, CacheFile_frame_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1048574.0f, 1048574.0f, -1048574.0f, 1048574.0f, 10.0f, 3, 0.0f, NULL
};

FloatPropertyRNA rna_CacheFile_frame_offset = {
	{(PropertyRNA *)&rna_CacheFile_forward_axis, (PropertyRNA *)&rna_CacheFile_frame,
	-1, "frame_offset", 3, 0, 0, 4, 0, "Frame Offset",
	"Subtracted from the current frame to use for looking up the data in the cache file, or to determine which file to use in a file sequence",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_CacheFile_update, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	offsetof(CacheFile, frame_offset), 5, NULL},
	CacheFile_frame_offset_get, CacheFile_frame_offset_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -1048574.0f, 1048574.0f, -1048574.0f, 1048574.0f, 10.0f, 3, 0.0f, NULL
};

static const EnumPropertyItem rna_CacheFile_forward_axis_items[7] = {
	{0, "POS_X", 0, "+X", ""},
	{1, "POS_Y", 0, "+Y", ""},
	{2, "POS_Z", 0, "+Z", ""},
	{3, "NEG_X", 0, "-X", ""},
	{4, "NEG_Y", 0, "-Y", ""},
	{5, "NEG_Z", 0, "-Z", ""},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_CacheFile_forward_axis = {
	{(PropertyRNA *)&rna_CacheFile_up_axis, (PropertyRNA *)&rna_CacheFile_frame_offset,
	-1, "forward_axis", 3, 0, 0, 0, 0, "Forward",
	"",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_CacheFile_update, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, NULL},
	CacheFile_forward_axis_get, CacheFile_forward_axis_set, NULL, NULL, NULL, NULL, rna_CacheFile_forward_axis_items, 6, 0
};

static const EnumPropertyItem rna_CacheFile_up_axis_items[7] = {
	{0, "POS_X", 0, "+X", ""},
	{1, "POS_Y", 0, "+Y", ""},
	{2, "POS_Z", 0, "+Z", ""},
	{3, "NEG_X", 0, "-X", ""},
	{4, "NEG_Y", 0, "-Y", ""},
	{5, "NEG_Z", 0, "-Z", ""},
	{0, NULL, 0, NULL, NULL}
};

EnumPropertyRNA rna_CacheFile_up_axis = {
	{(PropertyRNA *)&rna_CacheFile_scale, (PropertyRNA *)&rna_CacheFile_forward_axis,
	-1, "up_axis", 3, 0, 0, 0, 0, "Up",
	"",
	0, "*",
	PROP_ENUM, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_CacheFile_update, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, NULL},
	CacheFile_up_axis_get, CacheFile_up_axis_set, NULL, NULL, NULL, NULL, rna_CacheFile_up_axis_items, 6, 0
};

FloatPropertyRNA rna_CacheFile_scale = {
	{(PropertyRNA *)&rna_CacheFile_object_paths, (PropertyRNA *)&rna_CacheFile_up_axis,
	-1, "scale", 3, 0, 0, 4, 0, "Scale",
	"Value by which to enlarge or shrink the object with respect to the world\'s origin (only applicable through a Transform Cache constraint)",
	0, "*",
	PROP_FLOAT, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	rna_CacheFile_update, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	offsetof(CacheFile, scale), 5, NULL},
	CacheFile_scale_get, CacheFile_scale_set, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0.0001000000f, 1000.0f, 0.0001000000f, 1000.0f, 10.0f, 3, 0.0f, NULL
};

CollectionPropertyRNA rna_CacheFile_object_paths = {
	{(PropertyRNA *)&rna_CacheFile_animation_data, (PropertyRNA *)&rna_CacheFile_scale,
	-1, "object_paths", 0, 0, 0, 0, 0, "Object Paths",
	"Paths of the objects inside the Alembic archive",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, &RNA_AlembicObjectPaths},
	CacheFile_object_paths_begin, CacheFile_object_paths_next, CacheFile_object_paths_end, CacheFile_object_paths_get, NULL, CacheFile_object_paths_lookup_int, CacheFile_object_paths_lookup_string, NULL, &RNA_AlembicObjectPath
};

PointerPropertyRNA rna_CacheFile_animation_data = {
	{NULL, (PropertyRNA *)&rna_CacheFile_object_paths,
	-1, "animation_data", 8388608, 1, 0, 0, 0, "Animation Data",
	"Animation data for this data-block",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_AnimaData_override_apply,
	0, -1, NULL},
	CacheFile_animation_data_get, NULL, NULL, NULL,&RNA_AnimData
};

StructRNA RNA_CacheFile = {
	{(ContainerRNA *)&RNA_AlembicObjectPaths, (ContainerRNA *)&RNA_OperatorStrokeElement,
	NULL,
	{(PropertyRNA *)&rna_CacheFile_filepath, (PropertyRNA *)&rna_CacheFile_animation_data}},
	"CacheFile", NULL, NULL, 519, NULL, "CacheFile",
	"",
	"*", 184,
	(PropertyRNA *)&rna_ID_name, (PropertyRNA *)&rna_ID_rna_properties,
	&RNA_ID,
	NULL,
	rna_ID_refine,
	NULL,
	NULL,
	NULL,
	rna_ID_instance,
	rna_ID_idprops,
	{NULL, NULL}
};

/* Object Paths */
CollectionPropertyRNA rna_AlembicObjectPaths_rna_properties = {
	{(PropertyRNA *)&rna_AlembicObjectPaths_rna_type, NULL,
	-1, "rna_properties", 0, 0, 0, 1, 0, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, NULL},
	AlembicObjectPaths_rna_properties_begin, AlembicObjectPaths_rna_properties_next, AlembicObjectPaths_rna_properties_end, AlembicObjectPaths_rna_properties_get, NULL, NULL, AlembicObjectPaths_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_AlembicObjectPaths_rna_type = {
	{NULL, (PropertyRNA *)&rna_AlembicObjectPaths_rna_properties,
	-1, "rna_type", 8912896, 0, 0, 0, 0, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, NULL},
	AlembicObjectPaths_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

StructRNA RNA_AlembicObjectPaths = {
	{(ContainerRNA *)&RNA_AlembicObjectPath, (ContainerRNA *)&RNA_CacheFile,
	NULL,
	{(PropertyRNA *)&rna_AlembicObjectPaths_rna_properties, (PropertyRNA *)&rna_AlembicObjectPaths_rna_type}},
	"AlembicObjectPaths", NULL, NULL, 516, NULL, "Object Paths",
	"Collection of object paths",
	"*", 17,
	NULL, (PropertyRNA *)&rna_AlembicObjectPaths_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

/* Object Path */
CollectionPropertyRNA rna_AlembicObjectPath_rna_properties = {
	{(PropertyRNA *)&rna_AlembicObjectPath_rna_type, NULL,
	-1, "rna_properties", 0, 0, 0, 1, 0, "Properties",
	"RNA property collection",
	0, "*",
	PROP_COLLECTION, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, NULL},
	AlembicObjectPath_rna_properties_begin, AlembicObjectPath_rna_properties_next, AlembicObjectPath_rna_properties_end, AlembicObjectPath_rna_properties_get, NULL, NULL, AlembicObjectPath_rna_properties_lookup_string, NULL, &RNA_Property
};

PointerPropertyRNA rna_AlembicObjectPath_rna_type = {
	{(PropertyRNA *)&rna_AlembicObjectPath_path, (PropertyRNA *)&rna_AlembicObjectPath_rna_properties,
	-1, "rna_type", 8912896, 0, 0, 0, 0, "RNA",
	"RNA type definition",
	0, "*",
	PROP_POINTER, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {0, 0, 0}, 0,
	NULL, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, NULL},
	AlembicObjectPath_rna_type_get, NULL, NULL, NULL,&RNA_Struct
};

StringPropertyRNA rna_AlembicObjectPath_path = {
	{NULL, (PropertyRNA *)&rna_AlembicObjectPath_rna_type,
	-1, "path", 262145, 0, 0, 0, 0, "Path",
	"Object path",
	0, "*",
	PROP_STRING, PROP_NONE | PROP_UNIT_NONE, NULL, 0, {4096, 0, 0}, 0,
	NULL, 0, NULL, NULL, rna_property_override_diff_default, rna_property_override_store_default, rna_property_override_apply_default,
	0, -1, NULL},
	AlembicObjectPath_path_get, AlembicObjectPath_path_length, AlembicObjectPath_path_set, NULL, NULL, NULL, 4096, ""
};

StructRNA RNA_AlembicObjectPath = {
	{(ContainerRNA *)&RNA_Camera, (ContainerRNA *)&RNA_AlembicObjectPaths,
	NULL,
	{(PropertyRNA *)&rna_AlembicObjectPath_rna_properties, (PropertyRNA *)&rna_AlembicObjectPath_path}},
	"AlembicObjectPath", NULL, NULL, 516, NULL, "Object Path",
	"Path of an object inside of an Alembic archive",
	"*", 0,
	(PropertyRNA *)&rna_AlembicObjectPath_path, (PropertyRNA *)&rna_AlembicObjectPath_rna_properties,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	{NULL, NULL}
};

