# CMake generated Testfile for 
# Source directory: /Users/kobayashi/workspace/project/blender/source/blender/editors
# Build directory: /Users/kobayashi/workspace/project/build_darwin/source/blender/editors
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("animation")
subdirs("armature")
subdirs("curve")
subdirs("gpencil")
subdirs("interface")
subdirs("io")
subdirs("lattice")
subdirs("gizmo_library")
subdirs("mask")
subdirs("mesh")
subdirs("metaball")
subdirs("object")
subdirs("physics")
subdirs("render")
subdirs("scene")
subdirs("sculpt_paint")
subdirs("sound")
subdirs("space_action")
subdirs("space_api")
subdirs("space_buttons")
subdirs("space_clip")
subdirs("space_console")
subdirs("space_file")
subdirs("space_graph")
subdirs("space_image")
subdirs("space_info")
subdirs("space_nla")
subdirs("space_node")
subdirs("space_outliner")
subdirs("space_script")
subdirs("space_sequencer")
subdirs("space_statusbar")
subdirs("space_text")
subdirs("space_topbar")
subdirs("space_userpref")
subdirs("space_view3d")
subdirs("transform")
subdirs("undo")
subdirs("util")
subdirs("uvedit")
subdirs("screen")
subdirs("datafiles")
